---
- hosts: buildernodes
  gather_facts: no
  remote_user: pi
  become: yes
  become_method: sudo
  tasks:
    - import_tasks: tasks/init_squashfs.yml
    - import_tasks: tasks/preclone_hook_squashfs.yaml
    - import_tasks: tasks/middle_squashfs.yml
    - import_tasks: tasks/custom_hook_squashfs.yml
    - import_tasks: tasks/complete_squashfs.yml