---
- hosts: buildernodes
  gather_facts: no
  remote_user: pi
  become: yes
  become_method: sudo
  tasks:
    - name: sentinel start
      command: echo start
    - import_tasks: tasks/update_software.yml
    - import_tasks: tasks/reboot_and_wait.yml
    - import_tasks: tasks/initramfs.yml
    - import_tasks: tasks/init_squashfs.yml
    - import_tasks: tasks/preclone_hook_squashfs.yaml
    - import_tasks: tasks/middle_squashfs.yml
    - import_tasks: tasks/custom_hook_squashfs.yml
    - import_tasks: tasks/complete_squashfs.yml
    - name: sentinel done
      command: echo done