#!/bin/sh

set -e

PREREQ=""

prereqs () {
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/md5sum /bin
copy_exec /usr/bin/jq /bin
copy_exec /usr/bin/curl /bin
copy_exec /usr/local/bin/unionfs /bin/unionfs-fuse
copy_exec /usr/bin/strace /bin
copy_exec /bin/date /bin/gnudate
copy_exec /usr/bin/base64 /bin

# things needed to partition/prepare the sdcard if needed
copy_exec /sbin/fdisk /bin
copy_exec /sbin/sfdisk /bin
copy /sbin/mkfs /bin
copy /sbin/mkfs.bfs /bin
copy /sbin/mkfs.cramfs /bin
copy /sbin/mkfs.ext2 /bin
copy /sbin/mkfs.ext3 /bin
copy /sbin/mkfs.ext4 /bin
copy /sbin/mkfs.fat /bin
copy /sbin/mkfs.minix /bin
copy /sbin/mkfs.msdos /bin
copy /sbin/mkfs.vfat /bin

# make dns and ssl great again
cp -a /etc/ssl ${DESTDIR}/etc/ssl
mkdir -p ${DESTDIR}/usr/share/
echo "nameserver 8.8.8.8" > ${DESTDIR}/etc/resolv.conf
cp -a /usr/share/ca-certificates ${DESTDIR}/usr/share/      
cp -a /lib/arm-linux-gnueabihf/libnss_dns* ${DESTDIR}/lib/arm-linux-gnueabihf/

exit 0