#!/bin/sh

PREREQ="sdmount"

prereqs()
{
	echo "${PREREQ}"
}

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions

configure_networking
echo "cattlepi pre - cache and check"

curl http://192.168.0.1:4567/boot/23:45:34:33:33:12/config