#!/bin/sh

PREREQ="sdmount"

prereqs()
{
	echo "${PREREQ}"
}

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions
. scripts/cattlepi-base/helpers

configure_networking
echo "cattlepi pre - cache and check"
cattlepi_fetch_update_images
