#!/bin/sh

PREREQ="cachecheck"

prereqs()
{
	echo "${PREREQ}"
}

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

echo "cattlepi pre - sdmount RO"
umount /boot
mount -n -t vfat -o ro /dev/mmcblk0p1 /boot