- name: install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    force: yes
    state: latest
  with_items:
    - vim
    - busybox
    - initramfs-tools
    - squashfs-tools
    - git
    - libfuse-dev
    - jq
    - ufw
    - pv
- name: disable swap
  command: dphys-swapfile swapoff
- name: disable swap - make sure if does not come back
  command: dphys-swapfile uninstall
- name: ufw allow ssh connectivity
  shell: ufw allow ssh/tcp
- name: enable ufw (ufw is UncomplicatedFirewall)
  shell: yes | ufw enable
- name: upgrade packages and dist
  apt:
    upgrade: full