#!/bin/sh

PREREQ="cachecheck"

prereqs()
{
	echo "${PREREQ}"
}

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions
. /scripts/cattlepi-base/helpers

echo "cattlepi pre - sdmount RO"
cattlepi_sdmount_RO
echo "cattlepi pre - buildroot"
set -x
cattlepi_build_root_filesystem
echo "finished pre - buildroot"