#!/bin/sh

PREREQ="udev"

prereqs()
{
	echo "${PREREQ}"
}

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions
. /scripts/cattlepi-base/helpers

set -x

cattlepi_find_params

echo "cattlepi - sdmount"
cattlepi_sdmount

# If setting up wireless doesn't work, fall back to wired
configure_networking