#!/bin/sh

PREREQ="udev"

prereqs()
{
	echo "${PREREQ}"
}

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions
. /scripts/cattlepi-base/helpers

set -x

cattlepi_find_params

echo "cattlepi - sdmount"
cattlepi_sdmount

# If we have a wpa supplicant, try to set up wireless
if [ -r "${CATTLEPI_DIR}/wpa_supplicant.conf" ]; then
    cp "${CATTLEPI_DIR}/wpa_supplicant.conf" /etc/wpa_supplicant/wpa_supplicant.conf
    cattlepi_bring_up_wlan && exit 0
fi

# If setting up wireless doesn't work, fall back to wired
configure_networking