#!/bin/sh

PREREQ="udev"

prereqs()
{
	echo "${PREREQ}"
}

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /scripts/functions
. /scripts/cattlepi-base/helpers

set -x

cattlepi_find_params

echo "cattlepi - sdmount"
cattlepi_sdmount

echo "preprocess wpa supplicant"
cattlepi_unload_wpa_supplicant_if_not_needed

# echo "wpa supplicant initialization"
# # If we have a wpa supplicant, try to set up wireless
# if [ -r "${CATTLEPI_DIR}/wpa_supplicant.conf" ]; then
#     cattlepi_bring_up_wlan && exit 0
# fi

# If setting up wireless doesn't work, fall back to wired
configure_networking