#!/bin/sh

PREREQ="netup"

prereqs()
{
	echo "${PREREQ}"
}

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

echo "cattlepi pre - sdmount"
mkdir /boot
mount -n -t vfat /dev/mmcblk0p1 /boot