
require 'rake'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = '--color --format documentation'
end

require 'rubocop/rake_task'
RuboCop::RakeTask.new do |t|
  t.options << '--auto-correct'
end

task default: %i[rubocop spec]
