#!/bin/sh

set -e

PREREQ=""

prereqs () {
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/md5sum /bin
copy_exec /usr/bin/jq /bin
copy_exec /usr/bin/curl /bin
copy_exec /usr/bin/unionfs-fuse /bin
copy_exec /usr/bin/strace /bin

# the dns resolution so 
# seems that the resolver does some shady stuff 
# normally when picking up curl and deps this should work
set -x
for libnss_dns in `ldconfig -p | grep nss_dns | awk '{ print $8 }'` 
do
	copy_file library $(readlink -fn ${libnss_dns}) || echo "already in place"
	copy_file library $(readlink -fn ${libnss_dns}) /lib || echo "already in place"
	copy_file library ${libnss_dns} || echo "already in place"
	copy_file library ${libnss_dns} /lib || echo "already in place"
done

exit 0