#!/bin/sh

set -e

PREREQ=""

prereqs () {
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/md5sum /bin
copy_exec /usr/bin/jq /bin
copy_exec /usr/bin/curl /bin
copy_exec /usr/bin/unionfs-fuse /bin
copy_exec /usr/bin/strace /bin

exit 0
